CREATE TABLE IF NOT EXISTS user(
  UserID INTEGER PRIMARY KEY,
  Name VARCHAR(25),
  Email VARCHAR(25),
  CreatedAT TIMESTAMP
  );
CREATE TABLE IF NOT EXISTS mentor
  (mentorID INTEGER PRIMARY KEY,
  Name VARCHAR(25),
  Email VARCHAR(25),
  CreatedAT TIMESTAMP
  );
CREATE TABLE IF NOT EXISTS classes (
  classID INTEGER PRIMARY KEY,
  Title VARCHAR(40),
  mentorID INTEGER,
  Timing DATETIME,
  isEnded BOOLEAN,
  FOREIGN KEY (mentorID) REFERENCES mentor(mentorID)
);
CREATE TABLE IF NOT EXISTS task(
  taskID INTEGER PRIMARY KEY,
  Title VARCHAR(40),
  UserID INTEGER,
  Tag VARCHAR(30),
  FOREIGN KEY (UserID) REFERENCES user(UserID)
);

  


