CREATE TABLE IF NOT EXISTS User(
  UserID INTEGER PRIMARY KEY,
  Name VARCHAR(25),
  Email VARCHAR(25),
  CreatedAT TIMESTAMP
  );
CREATE TABLE IF NOT EXISTS Mentor
  (mentorID INTEGER PRIMARY KEY,
  Name VARCHAR(25),
  Email VARCHAR(25),
  CreatedAT TIMESTAMP
  );
CREATE TABLE IF NOT EXISTS Classes
  (classID INTEGER PRIMARY KEY,
  Title VARCHAR(40),
  mentorID INTEGER,
  Timing DATETIME,
  isEnded BOOLEAN
  );
